name: Daily College Basketball Data Update

on:
  schedule:
    # Runs at 7:10 AM EST (12:10 UTC)
    - cron: '10 12 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-r-scripts:
    runs-on: macos-latest
    env:
      CBD_USER: ${{ secrets.CBD_USER }}
      CBD_PW: ${{ secrets.CBD_PW }}
      GITHUB_PAT: ${{ secrets.GIT_TOKEN }}
    strategy:
      matrix:
        r-version: [4.2.0]
    
    # Set up R environment
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }} 

      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          install.packages(c("dplyr", "rvest", "readr", "glue", "purrr", "janitor", "here", "lubridate", "duckdb", "DBI", "zoo", "tidyr", "remotes", "devtools"))
          remotes::install_github("andreweatherman/cbbdata")
        shell: Rscript {0}
    
      - name: Create DuckDB Directory
        run: |
          mkdir -p ${{ github.workspace }}/sources/cbb
  
      - name: Create Data Directories
        run: |
          mkdir -p ${{ github.workspace }}/data
          mkdir -p ${{ github.workspace }}/sources/cbb
  
      - name: Run R Scripts
        run: |
          cd data/college-basketball
          Rscript wab_logs.R
          Rscript h2h_conf_records.R
          Rscript conf_standings.R
          Rscript net_archive.R
          Rscript team_sum_tbl.R
          Rscript tram.R
      
    # Optional: Commit and push changes if your scripts modify files
      - name: Commit results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update college basketball data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
