name: Daily College Basketball Data Update

on:
  #schedule:
    # Runs at 5:00 AM EST (10:00 UTC)
    # cron: '0 10 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-r-scripts:
    runs-on: macos-latest
    env:
      CBD_USER: ${{ secrets.CBD_USER }}
      CBD_PW: ${{ secrets.CBD_PW }}
      GITHUB_PAT: ${{ secrets.GIT_PAT }}
    strategy:
      matrix:
        r-version: [4.2.0]
    
    # Set up R environment
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          install.packages(c("dplyr", "rvest", "readr", "glue", "purrr", "janitor", "here", "lubridate", "duckdb", "DBI", "tidyr", "remotes", "devtools"))
          remotes::install_github("andreweatherman/cbbdata")
        shell: Rscript {0}
    
      - name: Create directory for DuckDB
        run: mkdir -p sources/cbb
  
      - name: Run R Scripts
        run: |
          cd data/college-basketball
          Rscript base_query.R
          Rscript conf_standings.R
          Rscript h2h_conf_records.R
          Rscript wab_logs.R
      
    # Optional: Commit and push changes if your scripts modify files
      - name: Commit results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update college basketball data" || echo "No changes to commit"
          git push
